### ISSUE TITLE
Mod ideas

### ISSUE THREAD

**Issue by yumi-modding** [Timmiej93/ModOverview#1]
Hello,
I read your mod ideas and I think these 2 ones are already addressed by great mod moreRealistic. Have a try if you don't know it.

Crop Density Simulation
Remove Harvesting Speed Limit

**Comment by Timmiej93** [comment]
I know of the MR mod, unfortunately I have never been able to use it in FS17 due to mod conflicts. I always prefer segmenting mods, instead of creating one big mod, so people can pick and choose the parts they want, while keeping the risk of mod conflicts as low as possible.
I appreciate you informing me about this though, could have saved me a lot of time.
